project:
  type: website
  resources: 
    - "images/twitter-card.jpg"
  
website:
  favicon: images/chakra.png
  title: "SaRa Institute"
  image: "images/twitter-card.jpg"
  site-url: https://saraedu.netlify.app/
  description: "Free data science education for underrepresented students."
  
  open-graph: true
  twitter-card:
    site: "@sara_institute" 
    creator: "@sara_institute" 
    image: "/images/twitter-card.jpg"
  
  navbar:
    left:
      - text: COURSES
        menu: 
          - text: List of courses
            href: courses.qmd
          - text: Admission requirements
            href: admission.qmd
      - text: ABOUT US  
        href: about.qmd
      - text: NEWS & EVENTS
        href: news.qmd
        
    right:  
      - text: CONTACT US
        href: contact.qmd
      - icon: github
        href: https://github.com/sara-edu
        aria-label: GitHub  
      - icon: twitter
        href: https://twitter.com/sara_institute
        aria-label: Twitter
      
  page-footer: 
    left:
      - text: "&copy; SaRa Institute 2023"
    center:
      - text: "Educate. Agitate. Organize."
    right:
      - href: contact.qmd
        text: Contact us
      - icon: github
        href: https://github.com/sara-edu
        aria-label: GitHub   
      - icon: twitter
        href: https://twitter.com/sara_institute
        aria-label: Twitter      

format:
  html:
    theme: [flatly, styles.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    page-layout: article
    fig-cap-location: bottom
    fig-responsive: true