project:
  type: website

website:
  title: "SARA Institute"
  
  navbar:
    right:
      - href: about.qmd
        text: ABOUT
      - href: courses.qmd
        text: COURSES
      - href: support.qmd
        text: SUPPORT US    
      - href: contact.qmd
        text: CONTACT
      - icon: twitter
        href: https://twitter.com/sara_institute
        aria-label: SARA Twitter
        
  page-footer: 
    left: "CC &copy;-By SARA Institute" 
    right:
      - icon: twitter
        href: https://twitter.com/sara_institute
        aria-label: Twitter 
        
format:
  html:
    theme: [flatly, styles.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap

editor: visual

